# Generated by Django 6.0 on 2026-01-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_created_at_alter_video_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_file',
            field=models.CharField(blank=True, help_text="Static thumbnail filename (e.g., 'havo.jpg')", max_length=100),
        ),
    ]
